### ISSUE TITLE
Site centering

### ISSUE THREAD

**Issue by ghost** [johnotander/pixyll#240] opened 2015-12-24 02:12 UTC
Hello,

I've noticed that center of my site differs when on main page and when on pages, and when I went to check this behavior on http://pixyll.com I noticed the same thing (in all browsers).

For instance, please visit http://pixyll.com/ then go to "Announcing Version 2.0" and you will see that in the latter site title and everything moves slightly to right.

Oddly, there is no issue in this regard with the next article "Hello, Pixyll" it is of same center as the main page site.

Now please go to "About" and again the center shifts to right.

Thank you.

**Comment by johnotander** [comment] 2016-01-03 21:17
I haven't been able to reproduce this myself. Could you please provide screenshots?

**Comment by keenam** [comment] 2016-01-04 10:42
I was just going to make a screen capture of my main desktop on Mac to show this behavior, but mysteriously, when I just prepared to do that, I was not able to reproduce this any longer, even though I experienced it just a moment ago.

The behavior I described I was, however, able to continue to experience on my old Windows machine.

Below is screen-cast using the current version of Firefox:
http://gph.is/1Z0sNQC

**Comment by johnotander** [comment] 2016-01-04 18:10
Thanks for the added info, @keenam, I will look into this later in the week when I have access to a Windows machine.

**Comment by keenam** [comment] 2016-01-05 03:02
Hello,
Once again, I was able to reproduce this on main desktop in all browsers. Please see the screen below:

https://youtu.be/5IJ8xgoRV0g

**Comment by johnotander** [comment] 2016-01-05 03:13
Yep, you are correct. I can clearly see it in the video. Thanks for documenting it :sunglasses: , I will do some digging later this week.

**Comment by adamzap** [comment] 2016-02-16 00:46
@keenam Isn't your scrollbar the issue? It's only appearing on pages where the content is long enough. The presence of the bar changes the centering.

You can add the following CSS rule to always show the scrollbar regardless of the content size:

```css
html {
  overflow-y: scroll;
}
```

That way every page will be consistently centered.

**Comment by johnotander** [comment] 2016-07-19 17:37
Closing since this appears to be solved by adding the CSS provided by @adamzap (thanks!). I'm going to opt out of adding it by default to Pixyll because I like the scrollbar being hidden when possible : )

Thanks for reporting! ✨ ✨ ✨

**Closed by johnotander** 2016-07-19 17:37 UTC
